export const data = [
	{type: 'element', title: 'H', number: '1', clazz: 'nonmetal', nameRu: 'Водород', nameEn: 'Hidrogen'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'element', title: 'He', number: '2', clazz: 'noble-gas', nameRu: 'Гелий', nameEn: ''},
	
	{type: 'element', title: 'Li', number: '3', clazz: 'alcali-metal', nameRu: 'Литий', nameEn: ''},
	{type: 'element', title: 'Be', number: '4', clazz: 'alcaline-earth-metal', nameRu: 'Бериллий', nameEn: ''},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'element', title: 'B', number: '5', clazz: 'metaloid', nameRu: 'Бор', nameEn: ''},
	{type: 'element', title: 'C', number: '6', clazz: 'nonmetal', nameRu: 'Углерод', nameEn: ''},
	{type: 'element', title: 'N', number: '7', clazz: 'nonmetal', nameRu: 'Азот', nameEn: ''},
	{type: 'element', title: 'O', number: '8', clazz: 'nonmetal', nameRu: 'Кислород', nameEn: ''},
	{type: 'element', title: 'F', number: '9', clazz: 'halogen', nameRu: 'Фтор', nameEn: ''},
	{type: 'element', title: 'Ne', number: '10', clazz: 'noble-gas', nameRu: 'Неон', nameEn: ''},
	
	{type: 'element', title: 'Na', number: '11', clazz: 'alcali-metal', nameRu: 'Натрий', nameEn: ''},
	{type: 'element', title: 'Mg', number: '12', clazz: 'alcaline-earth-metal', nameRu: 'Магний', nameEn: ''},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'element', title: 'Al', number: '13', clazz: 'post-transition-metal', nameRu: 'Алюминий', nameEn: ''},
	{type: 'element', title: 'Si', number: '14', clazz: 'metaloid', nameRu: 'Кремний', nameEn: ''},
	{type: 'element', title: 'P', number: '15', clazz: 'nonmetal', nameRu: 'Фосфор', nameEn: ''},
	{type: 'element', title: 'S', number: '16', clazz: 'nonmetal', nameRu: 'Сера', nameEn: ''},
	{type: 'element', title: 'Cl', number: '17', clazz: 'halogen', nameRu: 'Хлор', nameEn: ''},
	{type: 'element', title: 'Ar', number: '18', clazz: 'noble-gas', nameRu: 'Аргон', nameEn: ''},

	{type: 'element', title: 'K', number: '19', clazz: 'alcali-metal', nameRu: 'Калий', nameEn: ''},
	{type: 'element', title: 'Ca', number: '20', clazz: 'alcaline-earth-metal', nameRu: 'Кальций', nameEn: ''},
	{type: 'element', title: 'Sc', number: '21', clazz: 'transition-metal', nameRu: 'Скандий', nameEn: ''},
	{type: 'element', title: 'Ti', number: '22', clazz: 'transition-metal', nameRu: 'Титан', nameEn: ''},
	{type: 'element', title: 'V', number: '23', clazz: 'transition-metal', nameRu: 'Ванадий', nameEn: ''},
	{type: 'element', title: 'Cr', number: '24', clazz: 'transition-metal', nameRu: 'Хром', nameEn: ''},
	{type: 'element', title: 'Mn', number: '25', clazz: 'transition-metal', nameRu: 'Марганец', nameEn: ''},
	{type: 'element', title: 'Fe', number: '26', clazz: 'transition-metal', nameRu: 'Железо', nameEn: ''},
	{type: 'element', title: 'Co', number: '27', clazz: 'transition-metal', nameRu: 'Кобальт', nameEn: ''},
	{type: 'element', title: 'Ni', number: '28', clazz: 'transition-metal', nameRu: 'Никель', nameEn: ''},
	{type: 'element', title: 'Cu', number: '29', clazz: 'transition-metal', nameRu: 'Медь', nameEn: ''},
	{type: 'element', title: 'Zn', number: '30', clazz: 'transition-metal', nameRu: 'Цинк', nameEn: ''},
	{type: 'element', title: 'Ga', number: '31', clazz: 'post-transition-metal', nameRu: 'Галлий', nameEn: ''},
	{type: 'element', title: 'Ge', number: '32', clazz: 'metaloid', nameRu: 'Германий', nameEn: ''},
	{type: 'element', title: 'As', number: '33', clazz: 'metaloid', nameRu: 'Мышьяк', nameEn: ''},
	{type: 'element', title: 'Se', number: '34', clazz: 'nonmetal', nameRu: 'Селен', nameEn: ''},
	{type: 'element', title: 'Br', number: '35', clazz: 'halogen', nameRu: 'Бром', nameEn: ''},
	{type: 'element', title: 'Kr', number: '36', clazz: 'noble-gas', nameRu: 'Криптон', nameEn: ''},

	{type: 'element', title: 'Rb', number: '37', clazz: 'alcali-metal', nameRu: 'Рубидий', nameEn: ''},
	{type: 'element', title: 'Sr', number: '38', clazz: 'alcaline-earth-metal', nameRu: 'Стронций', nameEn: ''},
	{type: 'element', title: 'Y', number: '39', clazz: 'transition-metal', nameRu: 'Иттрий', nameEn: ''},
	{type: 'element', title: 'Zr', number: '40', clazz: 'transition-metal', nameRu: 'Циркон', nameEn: ''},
	{type: 'element', title: 'Nb', number: '41', clazz: 'transition-metal', nameRu: 'Ниобий', nameEn: ''},
	{type: 'element', title: 'Mo', number: '42', clazz: 'transition-metal', nameRu: 'Молибден', nameEn: ''},
	{type: 'element', title: 'Tc', number: '43', clazz: 'transition-metal', nameRu: 'Технеций', nameEn: ''},
	{type: 'element', title: 'Ru', number: '44', clazz: 'transition-metal', nameRu: 'Рутений', nameEn: ''},
	{type: 'element', title: 'Rh', number: '45', clazz: 'transition-metal', nameRu: 'Родий', nameEn: ''},
	{type: 'element', title: 'Pd', number: '46', clazz: 'transition-metal', nameRu: 'Палладий', nameEn: ''},
	{type: 'element', title: 'Ag', number: '47', clazz: 'transition-metal', nameRu: 'Серебро', nameEn: ''},
	{type: 'element', title: 'Cd', number: '48', clazz: 'transition-metal', nameRu: 'Кадмий', nameEn: ''},
	{type: 'element', title: 'In', number: '49', clazz: 'post-transition-metal', nameRu: 'Индий', nameEn: ''},
	{type: 'element', title: 'Sn', number: '50', clazz: 'post-transition-metal', nameRu: 'Олово', nameEn: ''},
	{type: 'element', title: 'Sb', number: '51', clazz: 'metaloid', nameRu: 'Сурьма', nameEn: ''},
	{type: 'element', title: 'Te', number: '52', clazz: 'metaloid', nameRu: 'Теллур', nameEn: ''},
	{type: 'element', title: 'I', number: '53', clazz: 'halogen', nameRu: 'Иод', nameEn: ''},
	{type: 'element', title: 'Xe', number: '54', clazz: 'noble-gas', nameRu: 'Ксенон', nameEn: ''},

	{type: 'element', title: 'Cs', number: '55', clazz: 'alcali-metal', nameRu: 'Цезий', nameEn: ''},
	{type: 'element', title: 'Ba', number: '56', clazz: 'alcaline-earth-metal', nameRu: 'Барий', nameEn: ''},
	{type: 'element', title: 'La', number: '57', clazz: 'transition-metal', nameRu: 'Лантан', nameEn: ''},
	{type: 'element', title: 'Hf', number: '72', clazz: 'transition-metal', nameRu: 'Гафний', nameEn: ''},
	{type: 'element', title: 'Ta', number: '73', clazz: 'transition-metal', nameRu: 'Тантал', nameEn: ''},
	{type: 'element', title: 'W', number: '74', clazz: 'transition-metal', nameRu: 'Вольфрам', nameEn: ''},
	{type: 'element', title: 'Re', number: '75', clazz: 'transition-metal', nameRu: 'Рений', nameEn: ''},
	{type: 'element', title: 'Os', number: '76', clazz: 'transition-metal', nameRu: 'Осмий', nameEn: ''},
	{type: 'element', title: 'Ir', number: '77', clazz: 'transition-metal', nameRu: 'Иридий', nameEn: ''},
	{type: 'element', title: 'Pt', number: '78', clazz: 'transition-metal', nameRu: 'Платина', nameEn: ''},
	{type: 'element', title: 'Au', number: '79', clazz: 'transition-metal', nameRu: 'Золото', nameEn: ''},
	{type: 'element', title: 'Hg', number: '80', clazz: 'transition-metal', nameRu: 'Ртуть', nameEn: ''},
	{type: 'element', title: 'Tl', number: '81', clazz: 'post-transition-metal', nameRu: 'Таллий', nameEn: ''},
	{type: 'element', title: 'Pb', number: '82', clazz: 'post-transition-metal', nameRu: 'Свинец', nameEn: ''},
	{type: 'element', title: 'Bi', number: '83', clazz: 'post-transition-metal', nameRu: 'Висмут', nameEn: ''},
	{type: 'element', title: 'Po', number: '84', clazz: 'metaloid', nameRu: 'Полоний', nameEn: ''},
	{type: 'element', title: 'At', number: '85', clazz: 'halogen', nameRu: 'Астат', nameEn: ''},
	{type: 'element', title: 'Rn', number: '86', clazz: 'noble-gas', nameRu: 'Радон', nameEn: ''},

	{type: 'element', title: 'Fr', number: '87', clazz: 'alcali-metal', nameRu: 'Франций', nameEn: ''},
	{type: 'element', title: 'Ra', number: '88', clazz: 'alcaline-earth-metal', nameRu: 'Радий', nameEn: ''},
	{type: 'element', title: 'Ac', number: '89', clazz: 'transition-metal', nameRu: 'Актиний', nameEn: ''},
	{type: 'element', title: 'Rf', number: '104', clazz: 'transition-metal', nameRu: 'Резерфордий', nameEn: ''},
	{type: 'element', title: 'Db', number: '105', clazz: 'transition-metal', nameRu: 'Дубний', nameEn: ''},
	{type: 'element', title: 'Sg', number: '106', clazz: 'transition-metal', nameRu: 'Сиборгий', nameEn: ''},
	{type: 'element', title: 'Bh', number: '107', clazz: 'transition-metal', nameRu: 'Борий', nameEn: ''},
	{type: 'element', title: 'Hs', number: '108', clazz: 'transition-metal', nameRu: 'Хассий', nameEn: ''},
	{type: 'element', title: 'Mt', number: '109', clazz: 'transition-metal', nameRu: 'Мейтнерий', nameEn: ''},
	{type: 'element', title: 'Ds', number: '110', clazz: 'transition-metal', nameRu: 'Дармштадтий', nameEn: ''},
	{type: 'element', title: 'Rg', number: '111', clazz: 'transition-metal', nameRu: 'Рентгений', nameEn: ''},
	{type: 'element', title: 'Cn', number: '112', clazz: 'transition-metal', nameRu: 'Коперниций', nameEn: ''},
	{type: 'element', title: 'Nh', number: '113', clazz: 'post-transition-metal', nameRu: 'Нихоний', nameEn: ''},
	{type: 'element', title: 'Fl', number: '114', clazz: 'post-transition-metal', nameRu: 'Флёровий', nameEn: ''},
	{type: 'element', title: 'Mc', number: '115', clazz: 'post-transition-metal', nameRu: 'Московий', nameEn: ''},
	{type: 'element', title: 'Lv', number: '116', clazz: 'post-transition-metal', nameRu: 'Ливерморий', nameEn: ''},
	{type: 'element', title: 'Ts', number: '117', clazz: 'post-transition-metal', nameRu: 'Теннессин', nameEn: ''},
	{type: 'element', title: 'Og',number: '118', clazz: 'noble-gas', nameRu: 'Оганесон', nameEn: ''},

	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},
	{type: 'blank low'},

	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'element', title: 'Ce', number: '58', clazz: 'lantanide', nameRu: 'Церий', nameEn: ''},
	{type: 'element', title: 'Pr', number: '59', clazz: 'lantanide', nameRu: 'Празеодим', nameEn: ''},
	{type: 'element', title: 'Nd', number: '60', clazz: 'lantanide', nameRu: 'Неодим', nameEn: ''},
	{type: 'element', title: 'Pm', number: '61', clazz: 'lantanide', nameRu: 'Прометий', nameEn: ''},
	{type: 'element', title: 'Sm', number: '62', clazz: 'lantanide', nameRu: 'Самарий', nameEn: ''},
	{type: 'element', title: 'Eu', number: '63', clazz: 'lantanide', nameRu: 'Европий', nameEn: ''},
	{type: 'element', title: 'Gd', number: '64', clazz: 'lantanide', nameRu: 'Гадолиний', nameEn: ''},
	{type: 'element', title: 'Tb', number: '65', clazz: 'lantanide', nameRu: 'Тербий', nameEn: ''},
	{type: 'element', title: 'Dy', number: '66', clazz: 'lantanide', nameRu: 'Диспрозий', nameEn: ''},
	{type: 'element', title: 'Ho', number: '67', clazz: 'lantanide', nameRu: 'Гольмий', nameEn: ''},
	{type: 'element', title: 'Er', number: '68', clazz: 'lantanide', nameRu: 'Эрбий', nameEn: ''},
	{type: 'element', title: 'Tm', number: '69', clazz: 'lantanide', nameRu: 'Тулий', nameEn: ''},
	{type: 'element', title: 'Yb', number: '70', clazz: 'lantanide', nameRu: 'Иттербий', nameEn: ''},
	{type: 'element', title: 'Lu', number: '71', clazz: 'lantanide', nameRu: 'Лютеций', nameEn: ''},
	{type: 'blank'},

	{type: 'blank'},
	{type: 'blank'},
	{type: 'blank'},
	{type: 'element', title: 'Th', number: '90', clazz: 'actinide', nameRu: 'Торий', nameEn: ''},
	{type: 'element', title: 'Pa', number: '91', clazz: 'actinide', nameRu: 'Проактиний', nameEn: ''},
	{type: 'element', title: 'U', number: '92', clazz: 'actinide', nameRu: 'Уран', nameEn: ''},
	{type: 'element', title: 'Np', number: '93', clazz: 'actinide', nameRu: 'Нептуний', nameEn: ''},
	{type: 'element', title: 'Pu', number: '94', clazz: 'actinide', nameRu: 'Плутоний', nameEn: ''},
	{type: 'element', title: 'Am', number: '95', clazz: 'actinide', nameRu: 'Америций', nameEn: ''},
	{type: 'element', title: 'Cm', number: '96', clazz: 'actinide', nameRu: 'Кюрий', nameEn: ''},
	{type: 'element', title: 'Bk', number: '97', clazz: 'actinide', nameRu: 'Берклий', nameEn: ''},
	{type: 'element', title: 'Cf', number: '98', clazz: 'actinide', nameRu: 'Калифорний', nameEn: ''},
	{type: 'element', title: 'Es', number: '99', clazz: 'actinide', nameRu: 'Эйнштейний', nameEn: ''},
	{type: 'element', title: 'Fm', number: '100', clazz: 'actinide', nameRu: 'Фермий', nameEn: ''},
	{type: 'element', title: 'Md', number: '101', clazz: 'actinide', nameRu: 'Менделеевий', nameEn: ''},
	{type: 'element', title: 'No', number: '102', clazz: 'actinide', nameRu: 'Нобелий', nameEn: ''},
	{type: 'element', title: 'Lr', number: '103', clazz: 'actinide', nameRu: 'Лоуренсий', nameEn: ''},
	{type: 'blank'},
]